name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable 
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run rustfmt
        run: cargo fmt --all --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        run: cargo test --all
